# Generated by Django 3.2.5 on 2021-08-11 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('annee', models.ManyToManyField(to='exam.Annee')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('annee', models.ManyToManyField(to='exam.Annee')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('coefficient', models.IntegerField()),
                ('annee', models.ManyToManyField(to='exam.Annee')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('filiere', models.ManyToManyField(to='exam.Filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.FloatField()),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
                ('notation', models.IntegerField()),
                ('id_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.controle')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseExacte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.reponse')),
            ],
        ),
        migrations.CreateModel(
            name='NoteExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.FloatField()),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.candidat')),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examen')),
                ('id_moyenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.moyenne')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.FloatField()),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.candidat')),
                ('id_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.controle')),
                ('id_moyenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.moyenne')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('filiere', models.ManyToManyField(to='exam.Filiere')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.FloatField()),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.candidat')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.module')),
                ('id_moyenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.moyenne')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.FloatField()),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.candidat')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.matiere')),
                ('id_moyenne_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.moyennemodule')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='module',
            field=models.ManyToManyField(to='exam.Module'),
        ),
        migrations.AddField(
            model_name='examen',
            name='id_matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.matiere'),
        ),
        migrations.AddField(
            model_name='controle',
            name='id_matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.matiere'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='controle',
            field=models.ManyToManyField(blank=True, null=True, to='exam.Controle'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='examen',
            field=models.ManyToManyField(blank=True, null=True, to='exam.Examen'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='id_filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.filiere'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='id_niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.niveau'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='reponse',
            field=models.ManyToManyField(blank=True, null=True, to='exam.Reponse'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
