# Generated by Django 3.2.5 on 2021-08-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyennematiere',
            name='id_moyenne_module',
        ),
        migrations.RemoveField(
            model_name='moyennemodule',
            name='id_moyenne',
        ),
    ]
